ARG NODE_VERSION=18.16.0

FROM node:${NODE_VERSION}-alpine AS node

FROM kong/kong-gateway:2.8.4.0
USER root

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN apk update && \
    apk add --no-cache python3 py3-pip python3-dev musl-dev libffi-dev gcc g++ file make curl jq
RUN npm install -g express json-server json-server-auth
RUN PYTHONWARNINGS=ignore pip3 install kong-pdk requests
COPY /plugins /usr/local/kong/python/

# reset back the defaults
USER kong
STOPSIGNAL SIGQUIT
HEALTHCHECK --interval=10s --timeout=10s --retries=10 CMD kong health
CMD ["bash", "/kong/declarative/startup-dbless.sh"]